### ISSUE TITLE
读取的数据盘不准确

### ISSUE THREAD

**Issue by cnhotfire** [Filecoin-Titan/titan#10]
我将titan放在/data目录下，data目录为4T空间。
/ 目录 系统盘为60G

titan节点显示的总存储空间 为60G， 我觉得这不合理。实际能提供4T的存储能力

**Comment by TitanNet** [comment]
@cnhotfire 
默认是跑在系统盘，如果要跑在其它盘需要设置这个环境变量
export EDGE_PATH=/your/edge/path

**Comment by ChangChihChiang** [comment]
Can you have complete instructions? In this way, we keep groping?

Poor experience

**Comment by TitanNet** [comment]
Hi @ChangChihChiang 
I agree with you very much, 
more detailed configuration documents are on the way
