### ISSUE TITLE
Requesting support for Docker image to test on NAS

### ISSUE THREAD

**Issue by yeahwong** [Filecoin-Titan/titan#3]
I really enjoy using your product and would like to perform some testing on my NAS. In order to make this process smoother, I am requesting support for Docker hub image so that I can test easily on my NAS. I believe this will provide more testing options for many users and offer a stable and reliable way to provide services. Even if you are unable to provide support for Docker images, I appreciate your attention and consideration towards my request.

**Comment by TitanNet** [comment]
Sir, I am sorry to reply to your message so late @yeahwong 

Titan has already released the Docker Image, but it is expected to be ready for testing after a week as the extranet registration function is not yet enabled.
Docker: https://hub.docker.com/repositories/nezha123
There are 2 Docker Images inside
titan-candidate: Suitable for devices with higher configurations, stored in IDC, with public IP.
titan-edge: Suitable for devices with lower configurations, stored at home, without public IP.
You can choose the appropriate Docker Image to run the test based on your own device
Docker files can be built by yourself：https://github.com/TongTianTaiShi/titan
How to use:
titan-candidate
docker run -d -v ~/.titancandidate:/root/.titancandidate -p 2345:2345 titan-candidate $NODE_ID $AREA_ID $LOCATOR_API_INFO
titan-edge
docker run -d -v ~/.titanedge:/root/.titanedge -p 1234:1234 titan-edge $NODE_ID $AREA_ID $LOCATOR_API_INFO

**Comment by yeahwong** [comment]
Thank you for your reply. However, we need a complete and functional Docker image.

**Comment by TitanNet** [comment]
Hi, @yeahwong 
sorry for replying so late.
At present, you can easily obtain the method to activate the Titan test node through the following two links.

https://titannetwork.notion.site/Titan-3463a508339242d4819679f1838204a8?pvs=4
https://github.com/Filecoin-Titan/titan/releases/tag/v0.1.10

**Comment by yeahwong** [comment]
docker image 怎么不更新了？

**Comment by yeahwong** [comment]
请问 $NODE_ID $AREA_ID $LOCATOR_API_INFO 怎么对应 LOCATOR_API_INFO 与 key？ 这里有两个参考啊？docker上有三个参数？

**Comment by TitanNet** [comment]
The new version of the program integrates these parameters into the Key

LOCATOR's currently used default
LOCATOR_API_INFO=https://39.108.143.56:5000

**Comment by TitanNet** [comment]
The docker image has not been updated yet, it is expected to be updated within this week

> docker image怎么不更新了？

**Comment by TitanNet** [comment]
You can check out the latest tutorial steps,
The previous tutorial was discarded.

https://titannetwork.notion.site/Titan-3463a508339242d4819679f1838204a8?pvs=4

**Comment by yeahwong** [comment]
> You can check out the latest tutorial steps, The previous tutorial was discarded.
> 
> https://titannetwork.notion.site/Titan-3463a508339242d4819679f1838204a8?pvs=4

那我等新的 docker 镜像吧，谢谢
