### ISSUE TITLE
What's wrong?

### ISSUE THREAD

**Issue by ChangChihChiang** [Filecoin-Titan/titan#9]
What's wrong? . How to solve it?![image](https://github.com/Filecoin-Titan/titan/assets/111222347/6a4a015c-24db-4563-bf13-5b02d51f5f27)

**Comment by TitanNet** [comment]
The error is "Timed out while pulling data from L1 candidate node, generally has no effect on normal operation of the node."
If there are many such cases, there may be a variety of reasons for this error
> 1. You need to check your network environment to see where there is a problem with the network;
> 2. It may also be caused by the high pressure on the candidate node when you visit the L1 candidate node;

这个错误是 “从 L1 候选节点 拉取数据时超时了，一般来说对节点的正常运行没有影响。”
如果这种情况有比较多，可能会有多种原因导致这个错误
> 1.需要检查你的网络环境，看看是哪里网络有问题；
> 2.也可能是你访问 L1候选节点 的时候，候选节点压力大导致的；

**Comment by ChangChihChiang** [comment]
Ping network is normal.
So I. Also stop testing. Reduce resources

Waiting for TITAN to stabilize. Complete. Let‘s test again.

Thank you
